In [ ]:
Problem 1:

In [ ]:
zoe@zoe-MS-7C75:~/Github/deep_learning_course$ source csci-e89/bin/activate
(csci-e89) zoe@zoe-MS-7C75:~/Github/deep_learning_course$ 
(csci-e89) zoe@zoe-MS-7C75:~/Github/deep_learning_course$ python --version
Python 3.10.21
(csci-e89) zoe@zoe-MS-7C75:~/Github/deep_learning_course$ pip --version
pip 23.0.1 from /home/zoe/Github/deep_learning_course/csci-e89/lib/python3.10/site-packages/pip (python 3.10)
(csci-e89) zoe@zoe-MS-7C75:~/Github/deep_learning_course$ 
(csci-e89) zoe@zoe-MS-7C75:~/Github/deep_learning_course$ pip list
Package                   Version
------------------------- ------------
absl-py                   2.5.0
anyio                     4.15.1
argon2-cffi               25.1.0
argon2-cffi-bindings      26.1.0
arrow                     1.4.0
asttokens                 3.0.2
astunparse                1.6.3
async-lru                 2.3.0
attrs                     26.1.0
babel                     2.18.0
beautifulsoup4            4.15.0
bleach                    6.4.0
certifi                   2026.7.22
cffi                      2.1.1
charset-normalizer        3.5.1
comm                      0.2.3
contourpy                 1.3.2
cycler                    0.12.1
debugpy                   1.8.21
decorator                 5.3.1
defusedxml                0.7.1
exceptiongroup            1.3.1
executing                 2.2.1
fastjsonschema            2.22.2
filelock                  3.32.3
flatbuffers               25.12.19
fonttools                 4.64.0
fqdn                      1.5.1
fsspec                    2026.7.0
gast                      0.7.0
google-pasta              0.2.0
grpcio                    1.83.1
h11                       0.16.0
h5py                      3.14.0
httpcore                  1.0.9
httpx                     0.28.1
idna                      3.19
ipykernel                 7.3.0
ipython                   8.39.0
isoduration               20.11.0
jedi                      0.20.0
Jinja2                    3.1.6
json5                     0.15.0
jsonpointer               3.1.1
jsonschema                4.26.0
jsonschema-specifications 2025.9.1
jupter                    0.1.0
jupyter_builder           1.2.3
jupyter_client            8.10.0
jupyter_core              5.9.1
jupyter-events            0.12.1
jupyter-lsp               2.3.1
jupyter_server            2.21.0
jupyter_server_terminals  0.5.4
jupyterlab                4.6.3
jupyterlab_pygments       0.3.0
jupyterlab_server         2.28.0
keras                     3.12.4
kiwisolver                1.5.1
lark                      1.3.1
libclang                  18.1.1
markdown-it-py            4.2.0
MarkupSafe                3.0.3
matplotlib                3.10.9
matplotlib-inline         0.2.2
mdurl                     0.1.2
mistune                   3.3.4
ml_dtypes                 0.6.0
mpmath                    1.3.0
namex                     0.1.0
nbclient                  0.11.0
nbconvert                 7.17.1
nbformat                  5.11.1
nest-asyncio2             1.7.2
networkx                  3.4.2
notebook                  7.6.2
notebook_shim             0.2.4
numpy                     2.2.6
nvidia-cublas-cu12        12.1.3.1
nvidia-cuda-cupti-cu12    12.1.105
nvidia-cuda-nvrtc-cu12    12.1.105
nvidia-cuda-runtime-cu12  12.1.105
nvidia-cudnn-cu12         9.1.0.70
nvidia-cufft-cu12         11.0.2.54
nvidia-curand-cu12        10.3.2.106
nvidia-cusolver-cu12      11.4.5.107
nvidia-cusparse-cu12      12.1.0.106
nvidia-nccl-cu12          2.21.5
nvidia-nvjitlink-cu12     12.9.86
nvidia-nvtx-cu12          12.1.105
opt_einsum                3.4.0
optree                    0.20.0
overrides                 7.7.0
packaging                 26.3
pandas                    2.3.3
pandocfilters             1.5.1
parso                     0.8.7
pexpect                   4.9.0
pillow                    12.3.0
pip                       23.0.1
platformdirs              4.11.7
prometheus_client         0.26.0
prompt_toolkit            3.0.53
protobuf                  7.36.1
psutil                    7.2.2
ptyprocess                0.7.0
pure_eval                 0.2.3
pycparser                 3.0
Pygments                  2.21.0
pyparsing                 3.3.2
python-dateutil           2.9.0.post0
python-json-logger        4.2.0
pytz                      2026.3.post1
PyYAML                    6.0.3
pyzmq                     27.2.0
referencing               0.37.0
requests                  2.34.2
rfc3339-validator         0.1.4
rfc3986-validator         0.1.1
rfc3987-syntax            1.1.0
rich                      15.0.0
rpds-py                   0.30.0
seaborn                   0.13.2
Send2Trash                2.1.0
setuptools                79.0.1
six                       1.17.0
soupsieve                 2.9.2
stack-data                0.6.3
sympy                     1.13.1
tensorflow                2.21.0
termcolor                 3.3.0
terminado                 0.18.1
tinycss2                  1.5.1
tomli                     2.4.1
torch                     2.5.1+cu121
torchaudio                2.5.1+cu121
torchvision               0.20.1+cu121
tornado                   6.5.8
traitlets                 5.16.1
triton                    3.1.0
typing_extensions         4.16.0
tzdata                    2026.3
uri-template              1.3.0
urllib3                   2.7.0
wcwidth                   0.8.3
webcolors                 25.10.0
webencodings              0.6.1
websocket-client          1.9.2
wheel                     0.48.0
wrapt                     2.4.0

[notice] A new release of pip is available: 23.0.1 -> 26.2.1
[notice] To update, run: pip install --upgrade pip
(csci-e89) zoe@zoe-MS-7C75:


Listing existing virtual environments:
zoe@zoe-MS-7C75:~$ find . -type d -name "*.venv" -o -name "venv"
./.local/share/Steam/steamapps/common/SteamLinuxRuntime_soldier/soldier_platform_2.0.20260602.240809/files/lib/python3.7/venv
./.local/share/Steam/steamapps/common/SteamLinuxRuntime_soldier/var/tmp-I1INS3/usr/lib/python3.7/venv
./.local/share/Steam/steamapps/common/SteamLinuxRuntime_4/steamrt4_platform_4.0.20260608.242786/files/lib/python3.13/venv
./.local/share/Steam/steamapps/common/SteamLinuxRuntime_4/var/tmp-JNGHS3/usr/lib/python3.13/venv
./.local/share/Trash/files/dl_venv/lib/python3.14/site-packages/jedi/third_party/typeshed/stdlib/venv
./Github/deep_learning_course/.venv
./Github/deep_learning_course/csci-e89/lib/python3.10/site-packages/jedi/third_party/typeshed/stdlib/venv
./.vscode/extensions/ms-python.python-2026.4.0-linux-x64/python_files/lib/jedilsp/jedi/third_party/typeshed/stdlib/3/venv
./.vscode/extensions/ms-python.vscode-pylance-2026.3.1/dist/typeshed-fallback/stdlib/venv
./.pyenv/versions/3.10.21/lib/python3.10/venv
zoe@zoe-MS-7C75:~$ pyenv versions
  system
* 3.10.21 (set by /home/zoe/.pyenv/version)
zoe@zoe-MS-7C75:~$ python --version
Python 3.10.21
zoe@zoe-MS-7C75:

In [ ]:
Problem 2:

In [ ]:
(csci-e89) zoe@zoe-MS-7C75:~/Github/deep_learning_course$ pip show tensorflow
Name: tensorflow
Version: 2.21.0
Summary: TensorFlow is an open source machine learning framework for everyone.
Home-page: https://www.tensorflow.org/
Author: Google Inc.
Author-email: packages@tensorflow.org
License: Apache 2.0
Location: /home/zoe/Github/deep_learning_course/csci-e89/lib/python3.10/site-packages
Requires: absl-py, astunparse, flatbuffers, gast, google_pasta, grpcio, h5py, keras, libclang, ml_dtypes, numpy, opt_einsum, packaging, protobuf, requests, setuptools, six, termcolor, typing_extensions, wrapt
Required-by: 
(csci-e89) zoe@zoe-MS-7C75:~/Github/deep_learning_course$ 

In [ ]:
Problem 3:

In [ ]:
(csci-e89) zoe@zoe-MS-7C75:~/Github/deep_learning_course$ python
Python 3.10.21 (main, Sep  5 2026, 16:26:22) [GCC 15.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
Ctrl click to launch VS Code Native REPL
>>> import tensorflow as tf
>>> my_tensor = tf.constant([[1, 2], [3, 4]])
>>> your_tensor = tf.constant([[5, 6], [7, 8]]
)
>>> result1 = my_tensor + your_tensor
>>> result1
<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 6,  8],
       [10, 12]], dtype=int32)>
>>> result2 = tf.add(my_tensor, your_tensor)
>>> result2
<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 6,  8],
       [10, 12]], dtype=int32)>
>>> 