In [4]:
import tensorflow as tf

In [5]:
tf.config.list_physical_devices('GPU')

[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [6]:
tf.constant([1, 2, 3])

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 3], dtype=int32)>

## Problem 1:
I created a Python virtual environment for this assignment using Python's built-in venv module rather than Conda. The environment was created with the command `python -m venv csci-e89` and activated using `source csci-e89/bin/activate`.

The virtual environment uses Python 3.10.21, which satisfies the requirement of Python 3.8 or higher. I also verified that pip is installed and available within the environment. The installed version is pip 23.0.1.

I used `pip list` to examine the packages installed in the virtual environment. The output is included below. I also examined the Python environments available on my system and verified that my system Python version is Python 3.10.21. Terminal output:

```bash
zoe@zoe-MS-7C75:~/Github/deep_learning_course$ source csci-e89/bin/activate
(csci-e89) zoe@zoe-MS-7C75:~/Github/deep_learning_course$ python --version
Python 3.10.21
(csci-e89) zoe@zoe-MS-7C75:~/Github/deep_learning_course$ pip --version
pip 23.0.1 from /home/zoe/Github/deep_learning_course/csci-e89/lib/python3.10/site-packages/pip (python 3.10)
(csci-e89) zoe@zoe-MS-7C75:~/Github/deep_learning_course$ pip list
Package                      Version
---------------------------- ---------------
absl-py                      2.5.0
anyio                        4.15.1
argon2-cffi                  25.1.0
argon2-cffi-bindings         26.1.0
arrow                        1.4.0
asttokens                    3.0.2
astunparse                   1.6.3
async-lru                    2.3.0
attrs                        26.1.0
babel                        2.18.0
beautifulsoup4               4.15.0
bleach                       6.4.0
certifi                      2026.7.22
cffi                         2.1.1
charset-normalizer           3.5.1
comm                         0.2.3
contourpy                    1.3.2
cycler                       0.12.1
debugpy                      1.8.21
decorator                    5.3.1
defusedxml                   0.7.1
exceptiongroup               1.3.1
executing                    2.2.1
fastjsonschema               2.22.2
filelock                     3.32.3
flatbuffers                  25.12.19
fonttools                    4.64.0
fqdn                         1.5.1
fsspec                       2026.7.0
gast                         0.7.0
google-pasta                 0.2.0
grpcio                       1.83.1
h11                          0.16.0
h5py                         3.14.0
httpcore                     1.0.9
httpx                        0.28.1
idna                         3.19
ipykernel                    7.3.0
ipython                      8.39.0
isoduration                  20.11.0
jedi                         0.20.0
Jinja2                       3.1.6
json5                        0.15.0
jsonpointer                  3.1.1
jsonschema                   4.26.0
jsonschema-specifications    2025.9.1
jupter                       0.1.0
jupyter_builder              1.2.3
jupyter_client               8.10.0
jupyter_core                 5.9.1
jupyter-events               0.12.1
jupyter-lsp                  2.3.1
jupyter_server               2.21.0
jupyter_server_terminals     0.5.4
jupyterlab                   4.6.3
jupyterlab_pygments          0.3.0
jupyterlab_server            2.28.0
keras                        3.12.4
kiwisolver                   1.5.1
lark                         1.3.1
libclang                     18.1.1
Markdown                     3.10.3
markdown-it-py               4.2.0
MarkupSafe                   3.0.3
matplotlib                   3.10.9
matplotlib-inline            0.2.2
mdurl                        0.1.2
mistune                      3.3.4
ml_dtypes                    0.6.0
mpmath                       1.3.0
namex                        0.1.0
nbclient                     0.11.0
nbconvert                    7.17.1
nbformat                     5.11.1
nest-asyncio2                1.7.2
networkx                     3.4.2
notebook                     7.6.2
notebook_shim                0.2.4
numpy                        2.1.3
nvidia-cublas-cu12           12.1.3.1
nvidia-cuda-cupti-cu12       12.1.105
nvidia-cuda-nvrtc-cu12       12.1.105
nvidia-cuda-runtime-cu12     12.1.105
nvidia-cudnn-cu12            9.1.0.70
nvidia-cufft-cu12            11.0.2.54
nvidia-curand-cu12           10.3.2.106
nvidia-cusolver-cu12         11.4.5.107
nvidia-cusparse-cu12         12.1.0.106
nvidia-nccl-cu12             2.21.5
nvidia-nvjitlink-cu12        12.9.86
nvidia-nvtx-cu12             12.1.105
opt_einsum                   3.4.0
optree                       0.20.0
overrides                    7.7.0
packaging                    26.3
pandas                       2.3.3
pandocfilters                1.5.1
parso                        0.8.7
pexpect                      4.9.0
pillow                       12.3.0
pip                          23.0.1
platformdirs                 4.11.7
prometheus_client            0.26.0
prompt_toolkit               3.0.53
protobuf                     5.29.6
psutil                       7.2.2
ptyprocess                   0.7.0
pure_eval                    0.2.3
pycparser                    3.0
Pygments                     2.21.0
pyparsing                    3.3.2
python-dateutil              2.9.0.post0
python-json-logger           4.2.0
pytz                         2026.3.post1
PyYAML                       6.0.3
pyzmq                        27.2.0
referencing                  0.37.0
requests                     2.34.2
rfc3339-validator            0.1.4
rfc3986-validator            0.1.1
rfc3987-syntax               1.1.0
rich                         15.0.0
rocm                         7.14.1
rocm-sdk-core                7.14.1
rocm-sdk-device-gfx1010      7.14.1
rocm-sdk-device-gfx1011      7.14.1
rocm-sdk-device-gfx1012      7.14.1
rocm-sdk-device-gfx1030      7.14.1
rocm-sdk-device-gfx1031      7.14.1
rocm-sdk-device-gfx1032      7.14.1
rocm-sdk-device-gfx1033      7.14.1
rocm-sdk-device-gfx1034      7.14.1
rocm-sdk-device-gfx1035      7.14.1
rocm-sdk-device-gfx1036      7.14.1
rocm-sdk-device-gfx1100      7.14.1
rocm-sdk-device-gfx1101      7.14.1
rocm-sdk-device-gfx1102      7.14.1
rocm-sdk-device-gfx1103      7.14.1
rocm-sdk-device-gfx1150      7.14.1
rocm-sdk-device-gfx1151      7.14.1
rocm-sdk-device-gfx1152      7.14.1
rocm-sdk-device-gfx1153      7.14.1
rocm-sdk-device-gfx1200      7.14.1
rocm-sdk-device-gfx1201      7.14.1
rocm-sdk-device-gfx1250      7.14.1
rocm-sdk-device-gfx908       7.14.1
rocm-sdk-device-gfx90a       7.14.1
rocm-sdk-device-gfx942       7.14.1
rocm-sdk-device-gfx950       7.14.1
rocm-sdk-libraries           7.14.1
rpds-py                      0.30.0
seaborn                      0.13.2
Send2Trash                   2.1.0
setuptools                   79.0.1
six                          1.17.0
soupsieve                    2.9.2
stack-data                   0.6.3
sympy                        1.14.0
tensorboard                  2.19.0
tensorboard-data-server      0.7.2
tensorflow-io-gcs-filesystem 0.37.1
tensorflow_rocm              2.19.1
termcolor                    3.3.0
terminado                    0.18.1
tinycss2                     1.5.1
tomli                        2.4.1
torch                        2.14.0+rocm7.14
torchvision                  0.29.0+rocm7.14
tornado                      6.5.8
traitlets                    5.16.1
triton                       3.1.0
triton-rocm                  3.8.0
typing_extensions            4.16.0
tzdata                       2026.3
uri-template                 1.3.0
urllib3                      2.7.0
wcwidth                      0.8.3
webcolors                    25.10.0
webencodings                 0.6.1
websocket-client             1.9.2
Werkzeug                     3.1.8
wheel                        0.48.0
wrapt                        2.4.0

[notice] A new release of pip is available: 23.0.1 -> 26.2.1
[notice] To update, run: pip install --upgrade pip
(csci-e89) zoe@zoe-MS-7C75:~/Github/deep_learning_course$ 



Listing existing virtual environments:
zoe@zoe-MS-7C75:~$ find . -type d -name "*.venv" -o -name "venv"
./.local/share/Steam/steamapps/common/SteamLinuxRuntime_soldier/soldier_platform_2.0.20260602.240809/files/lib/python3.7/venv
./.local/share/Steam/steamapps/common/SteamLinuxRuntime_soldier/var/tmp-I1INS3/usr/lib/python3.7/venv
./.local/share/Steam/steamapps/common/SteamLinuxRuntime_4/steamrt4_platform_4.0.20260608.242786/files/lib/python3.13/venv
./.local/share/Steam/steamapps/common/SteamLinuxRuntime_4/var/tmp-JNGHS3/usr/lib/python3.13/venv
./.local/share/Trash/files/dl_venv/lib/python3.14/site-packages/jedi/third_party/typeshed/stdlib/venv
./Github/deep_learning_course/.venv
./Github/deep_learning_course/csci-e89/lib/python3.10/site-packages/jedi/third_party/typeshed/stdlib/venv
./.vscode/extensions/ms-python.python-2026.4.0-linux-x64/python_files/lib/jedilsp/jedi/third_party/typeshed/stdlib/3/venv
./.vscode/extensions/ms-python.vscode-pylance-2026.3.1/dist/typeshed-fallback/stdlib/venv
./.pyenv/versions/3.10.21/lib/python3.10/venv
zoe@zoe-MS-7C75:~$ pyenv versions
  system
* 3.10.21 (set by /home/zoe/.pyenv/version)
zoe@zoe-MS-7C75:~$ python --version
Python 3.10.21
zoe@zoe-MS-7C75:
```

## Problem 2:

Because my local computer has an AMD GPU, I installed the ROCm-supported version of TensorFlow instead of the CUDA-supported TensorFlow installation. 

The installed TensorFlow version is TensorFlow ROCm 2.19.1, which satisfies the assignment requirement of TensorFlow 2.10 or higher. I verified the installed version and package information using pip show tensorflow_rocm.

See the output below for package information and installation details: 

```bash
(csci-e89) zoe@zoe-MS-7C75:~/Github/deep_learning_course$ pip show tensorflow_rocm
Name: tensorflow_rocm
Version: 2.19.1
Summary: TensorFlow is an open source machine learning framework for everyone.
Home-page: https://www.tensorflow.org/
Author: Google Inc.
Author-email: packages@tensorflow.org
License: Apache 2.0
Location: /home/zoe/Github/deep_learning_course/csci-e89/lib/python3.10/site-packages
Requires: absl-py, astunparse, flatbuffers, gast, google-pasta, grpcio, h5py, keras, libclang, ml-dtypes, numpy, opt-einsum, packaging, protobuf, requests, setuptools, six, tensorboard, tensorflow-io-gcs-filesystem, termcolor, typing-extensions, wrapt
Required-by: 
(csci-e89) zoe@zoe-MS-7C75:~/Github/deep_learning_course$ 
```

## Problem 3:

In this problem, I imported TensorFlow and created two simple 2×2 tensors. I then added the tensors using both + and the TensorFlow tf.add() function.

Both methods produced the same resulting tensor:

[[ 6  8]
 [10 12]]

The code I used for this is below:

In [7]:
import tensorflow as tf
my_tensor = tf.constant([[1, 2], [3, 4]])
your_tensor = tf.constant([[5, 6], [7, 8]])
result1 = my_tensor + your_tensor
print(result1)

result2 = tf.add(my_tensor, your_tensor)
print(result2)




tf.Tensor(
[[ 6  8]
 [10 12]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[ 6  8]
 [10 12]], shape=(2, 2), dtype=int32)


## Problem 4:

I ran the provided CPU-versus-GPU test in my local TensorFlow environment. My computer has an AMD GPU, so my TensorFlow installation uses ROCm rather than CUDA.

I first verified that TensorFlow was built with ROCm support and that a physical GPU was available. TensorFlow reported that ROCm support was enabled and detected one physical GPU:

```
TensorFlow: 2.19.1
Built with ROCm: True
GPUs: [PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]
```

I then performed the matrix multiplication test using both the CPU and GPU. The test performs 50 matrix multiplications for each device.

The resulting execution times were:

CPU: 25.9809 seconds
GPU: 0.00406 seconds

As expected, the GPU was much faster than the CPU for this matrix multiplication. 

The code is below:


In [8]:
import tensorflow as tf
import timeit

In [9]:
dir(timeit)

['Timer',
 '__all__',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__spec__',
 '_globals',
 'default_number',
 'default_repeat',
 'default_timer',
 'dummy_src_name',
 'gc',
 'itertools',
 'main',
 'reindent',
 'repeat',
 'sys',
 'template',
 'time',
 'timeit']

## check physical GPU availability

In [10]:
# returns whether TensorFlow was built with CUDA (GPU) support
tf.test.is_built_with_rocm()

True

In [11]:
# returns a list of available physical GPUs
tf.config.list_physical_devices("GPU")

[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [12]:
import tensorflow as tf

print("TensorFlow:", tf.__version__)
print("Built with ROCm:", tf.test.is_built_with_rocm())
print("GPUs:", tf.config.list_physical_devices("GPU"))

TensorFlow: 2.21.0-dev0+selfbuilt
Built with ROCm: True
GPUs: [PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]


In [13]:
# returns the names of physical GPUs
tf.test.gpu_device_name()

I0000 00:00:1789172635.840859   52171 gpu_device.cc:2043] Created device /device:GPU:0 with 15628 MB memory:  -> device: 0, name: AMD Radeon RX 6800 XT, pci bus id: 0000:03:00.0


'/device:GPU:0'

## a test case

In [14]:
# initialize random matrices on CPU and GPU
with tf.device("/CPU:0"):
    cpu_m1 = tf.random.normal(shape=[10000, 1000])
    cpu_m2 = tf.random.normal(shape=[1000, 5000])
    print(cpu_m1.device, "\n", cpu_m2.device, "\n"*2)

with tf.device("/GPU:0"):
    gpu_m1 = tf.random.normal([10000, 1000])
    gpu_m2 = tf.random.normal([1000, 5000])
    print(gpu_m1.device, "\n", gpu_m2.device)

/job:localhost/replica:0/task:0/device:CPU:0 
 /job:localhost/replica:0/task:0/device:CPU:0 


/job:localhost/replica:0/task:0/device:GPU:0 
 /job:localhost/replica:0/task:0/device:GPU:0


In [15]:
# perform matrix multiplication test
def cpu_test():
    with tf.device("/CPU:0"):
        res = tf.matmul(cpu_m1, cpu_m2)
    return res

def gpu_test():
    with tf.device("/GPU:0"):
        res = tf.matmul(gpu_m1, gpu_m2)
    return res

if __name__ == "__main__":
    cpu_time = timeit.timeit(cpu_test, number=50)
    gpu_time = timeit.timeit(gpu_test, number=50)
    print(f"CPU run time: {cpu_time}\nGPU run time: {gpu_time}")

CPU run time: 26.850418441999864
GPU run time: 0.2221909830000186


Problem 5:

Using the default CPU
CPU run time: 102.79185575499992
GPU run time: 97.17132322200007

Using a T4 GPU:
CPU run time: 56.61730505500003
GPU run time: 0.13131591600000547



Problem 6: